language: csharp
mono: none
dotnet: 2.1.4
install:
- dotnet restore src/
script:
- dotnet build --configuration Release src/
- dotnet test test/Shoppy.Tests/Shoppy.Tests.csproj
deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true
notifications:
  slack:
    secure: nEgRyraASP6fTLrsn7cTKtvW4FK1orqySQJU0pXPQs5ItoYE5Cf7jkY4rFP+urnYv0nLQmcpY6oMYfsWsSqx5EnrDGIl/iOk9jq2KysJUWs/DiZsG50D8ihr2LyDfrmvOA/jTw+ESfgHa44sohUcqOZ4FdStpKZNatvwa61dn9u1Hu2TiKRs6b3ol9R3S0ZwCCzny0lAVBUzo3uqgj9NSXppDnEcfnvWfAH58ErlKmhG8ulOv/8FV0FMdDbKPOXL5drkTpMuy8pcjHKK9+vencgw/SufVQBN99UZVU5AhQI+rHJ6LwcINpSr5Ccc+Nwutcp0VwPUK+xnj4cG5Ewl1gyHi+RZtLE3PdchiiXqUP6ituY3M0ts+qD7/6irXU1tgzAlijc6JKp6M4RcXCLK3tNnye0AUcQ6BXY3dpwRw26iM7btYbuOfDoHso87oQscTOtvOd3h0/IzbHjKYK3OF6tMSk7VsF6l8oQ2fdZINH4Uy4Jngys4h8TKwl1OjUr6kHHpx6WUEsdIl5TT1UpDeeLguSuRdar1ibySJays4PZEG+UjiIfyhdEXFZ3wy8uPXfRHxPNfN3g8uoVTioHSfvRE3uHzrZsdKECEuOxu8McNXExHKld9nLXquWYsQqPDMtrAq5gX6a0ESBnFQ8ZTXtNzmKeIZqK4aWmk36sOnwg=
